routes/web.php
<?php

Route::get('/privacy', 'FrontController@privacyPolicy');

//AUTH
Route::get('forcelogin', 'Auth\LoginController@forceLogin')->name('forcelogin');
Route::get('login', 'Auth\LoginController@index')->name('login');
Route::post('login', 'Auth\LoginController@auth');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::any('reset-password', 'Auth\LoginController@resetForm')->name('reset_form');
Route::get('reset/{token}', 'Auth\LoginController@resetPassword')->name('reset');
Route::post('update_password', 'Auth\LoginController@updatePassword')->name('update_password');

//REGISTER
Route::get('daftar', 'Student\RegisterController@index')->name('daftar');
Route::post('daftar', 'Student\RegisterController@store');

Route::get('partner', 'FrontController@partner');
Route::post('partner', 'FrontController@partnerRegister');

//MENU
Route::get('/', 'FrontController@index');
Route::post('check_email', 'Front\OrderController@check_email')->name('check_email');
Route::post('order', 'Front\OrderController@order')->name('order');
Route::resource('kelas', 'Front\KelasController');
Route::post('kelas/check_promo_code', 'Front\KelasController@check_promo_code')->name('kelas.check_promo_code');
Route::get('checkout/{slug}', 'Front\KelasController@checkout');

// Student Auth Controller
Route::middleware(['auth'])->prefix('student')->namespace('Student')->name('student.')->group(function () {
    Route::resource('kelas', 'KelasController');
//    Route::get('kelas/{slug}/{lesson}', 'KelasController@lesson');
    Route::resource('lesson', 'LessonController');
});

// Partner Auth Controller
Route::middleware(['auth'])->prefix('partner')->namespace('Partner')->name('partner.')->group(function () {
    Route::resource('profile', 'PartnerController');
    Route::resource('voucher', 'VoucherController');
});

// Admin Auth Controller
Route::redirect('/admin', '/admin/kelas');
Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->name('admin.')->group(function () {
    Route::resource('kelas', 'KelasController');
    Route::post('kelas/reorder','KelasController@reorder')->name('kelas.reorder');
});

app/Http/Controllers/Student/KelasController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Requests\UpdateProfileRequest;
use App\Repositories\EnrollmentRepository;
use App\Repositories\KelasRepository;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

use Illuminate\Support\Facades\Auth;

class KelasController extends Controller
{
    private $kelasRepository;

    public function __construct(KelasRepository $kelasRepository)
    {
        $this->kelasRepository = $kelasRepository;
    }
    public function index()
    {
        $userCourse = (new EnrollmentRepository())->getUserCourse();
        return view('student.kelas.index',compact('userCourse'));
    }

    public function create()
    {
        # code...
    }

    public function store()
    {
        # code...
    }

    public function show(Request $request, $slug)
    {
//        dd($request->lesson);
        $kelas = $this->kelasRepository->findBySlug($slug);
        $sections = $this->kelasRepository->getSections('course',$kelas->id);
        return view('student.kelas.show',compact('kelas','sections'));
    }

    public function update(UpdateProfileRequest $request)
    {
        $request->validated();
        (new UserRepository())->update(Auth::id(), ['bank_name' => $request->bank_name, 'bank_no_rekening' => $request->bank_no_rekening, 'ktp' => $request->ktp]);
        return redirect()->route('partner.voucher.index')->with('success', 'Data berhasil disimpan');

    }

    public function destroy($id)
    {
        # code...
    }
}

app/Http/Controllers/Student/LessonController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Repositories\LessonRepository;
use Illuminate\Http\Request;

class LessonController extends Controller
{
    private $lessonRepository;

    public function __construct(LessonRepository $lessonRepository)
    {
        $this->lessonRepository = $lessonRepository;
    }
    public function index()
    {
    }
    public function show($id)
    {
    }

}

app/Http/Controllers/Student/RegisterController.php
<?php


namespace App\Http\Controllers\Student;


use App\Http\Controllers\Controller;
use App\Http\Requests\RegisterRequest;
use App\Repositories\UserRepository;
use Illuminate\Support\Facades\Auth;

class RegisterController extends Controller
{
    public function index()
    {
        return view('student.register.index');
    }
    public function store(RegisterRequest $request)
    {
        $request->validated();
        $user = (new UserRepository())->create([
            'name' => $request->name,
            'email' => $request->email,
            'handphone' => $request->handphone,
            'password' => bcrypt($request->password),
            'is_student' => 1
        ]);
        if ($user) {
            Auth::loginUsingId($user->id);
            return redirect()->route('student.kelas.index');
        }
        return back()->withErrors(["Pendaftaran gagal, silakan coba lagi!"]);

    }

}

app/Http/Controllers/Student/StudentController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Requests\UpdateProfileRequest;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

use Illuminate\Support\Facades\Auth;

class StudentController extends Controller
{
    public function __construct()
    {
        # code...
    }

    public function index()
    {
        $partner = (new UserRepository())->findById(Auth::id());
        return view('partner.profile', compact('partner'));
    }

    public function create()
    {
        # code...
    }

    public function store()
    {
        # code...
    }

    public function edit($id)
    {
    }

    public function update(UpdateProfileRequest $request)
    {
        $request->validated();
        (new UserRepository())->update(Auth::id(), ['bank_name' => $request->bank_name, 'bank_no_rekening' => $request->bank_no_rekening, 'ktp' => $request->ktp]);
        return redirect()->route('partner.voucher.index')->with('success', 'Data berhasil disimpan');

    }

    public function destroy($id)
    {
        # code...
    }
}

resources/views/student/layout/layout.blade.php
<!DOCTYPE html>
<html lang="id-ID.utf8">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@yield('title')</title>

    <!-- Main theme -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather:300,400,700|Montserrat:300,400,500,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{{url('assets/student')}}/css/style.css">
    <link rel="stylesheet" href="{{url('assets/student')}}/css/plyr.css">
</head>

<body>
@include('student.layout.sidebar');
@yield('content')
@yield('mobile')
<script src="{{url('assets/student')}}/scripts/jquery-latest.min.js" type="text/javascript"></script>
<script src="{{url('assets/student')}}/scripts/bootstrap.min.js" type="text/javascript"></script>
<script src="{{url('assets/student')}}/scripts/main.js" type="text/javascript"></script>

<script type="text/javascript"></script>

</body>

</html>

resources/views/student/layout/sidebar.blade.php
<!-- begin sidebar -->
<aside class="sidebar d-none d-sm-block">
    <div class="card">
        <div class="card-body text-center">
            <div class="avatar embed-responsive embed-responsive-1by1 mx-auto" style="width:100px; height: 120px;">
                <div class="frame frame__active ">
                    <img class="img-avatar" src="{{url('')}}/assets/student/images/default-avatar.svg" alt="avatar" />
                </div>
            </div>
            <h5 class="card-name mt-2">{{auth()->user()->name}}</h5>

            <span class="">Student</span>
            <!-- <span class="mt-2 d-flex align-items-center badge-pro-bwa badge-primary">PRO <i class="material-icons">
                stars
              </i></span> -->
        </div>
    </div>

    <ul class="nav nav__main-menu flex-column">
        <li class="nav-item">
            <h6 class="nav-heading">Main Menu</h6>
        </li>
{{--        <li class="nav-item">--}}
{{--            <a class="nav-link " href="{{url('')}}/student/progress_belajar">Progress Belajar</a>--}}
{{--        </li>--}}
        <li class="nav-item ">
            <a class="nav-link active" href="{{url('')}}/student/kelas">Kelas Saya</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " target="_blank" href="{{url('')}}/kelas">Katalog Kelas</a>
        </li>
    </ul>

    <ul class="nav nav__main-menu flex-column">
{{--        <li class="nav-item">--}}
{{--            <h6 class="nav-heading">Akun Saya</h6>--}}
{{--        </li>--}}
{{--        <li class="nav-item">--}}
{{--            <a class="nav-link " href="{{url('')}}/edit_profile">Edit Profil</a>--}}
{{--        </li>--}}
{{--        <li class="nav-item">--}}
{{--            <a class="nav-link " href="{{url('')}}/edit_password">Security Password</a>--}}
{{--        </li>--}}
        <li class="nav-item">
            <a class="nav-link" href="{{url('')}}/logout">Keluar</a>
        </li>
    </ul>
</aside>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>  <!-- end of sidebar -->

resources/views/student/layout/user.blade.php
<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <span class="hidden-xs">{{ auth()->user()->name }}</span>
    </a>
    <ul class="dropdown-menu">
        <li class="user-header">
            <p>
                {{ auth()->user()->name }}
                <small>Member since {{ auth()->user()->created_at->format('M Y') }}</small>
            </p>
        </li>
        <li class="user-footer">
            <div class="pull-left">
                <a href="{{ route('partner.profile.index') }}" class="btn btn-default btn-flat">Profile</a>
            </div>
            <div class="pull-right">
                <a href="{{ url('logout') }}" class="btn btn-default btn-flat">Sign out</a>
            </div>
        </li>
    </ul>
</li>

resources/views/student/layout/validation.blade.php
@if ($errors->any())
    <div class="alert alert-danger alert-styled-left alert-dismissible">
        <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
        <span class="font-weight-semibold">Whoops! Validation Error</span> <br>
        <ul style="padding-left:20px">
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
        </ul>
    </div>
@endif

@if(session()->has('success'))
    <div class="alert alert-success alert-styled-left alert-arrow-left alert-dismissible">
        <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
        {{ session('success') }}
    </div>
@endif