routes/web.php
<?php

Route::get('/privacy', 'FrontController@privacyPolicy');

//AUTH
Route::get('forcelogin', 'Auth\LoginController@forceLogin')->name('forcelogin');
Route::get('login', 'Auth\LoginController@index')->name('login');
Route::post('login', 'Auth\LoginController@auth');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::any('reset-password', 'Auth\LoginController@resetForm')->name('reset_form');
Route::get('reset/{token}', 'Auth\LoginController@resetPassword')->name('reset');
Route::post('update_password', 'Auth\LoginController@updatePassword')->name('update_password');

//REGISTER
Route::get('daftar', 'Student\RegisterController@index')->name('daftar');
Route::post('daftar', 'Student\RegisterController@store');

Route::get('partner', 'FrontController@partner');
Route::post('partner', 'FrontController@partnerRegister');

//MENU
Route::get('/', 'FrontController@index');
Route::post('check_email', 'Front\OrderController@check_email')->name('check_email');
Route::post('order', 'Front\OrderController@order')->name('order');
Route::resource('kelas', 'Front\KelasController');
Route::post('kelas/check_promo_code', 'Front\KelasController@check_promo_code')->name('kelas.check_promo_code');
Route::get('checkout/{slug}', 'Front\KelasController@checkout');

// Student Auth Controller
Route::middleware(['auth'])->prefix('student')->namespace('Student')->name('student.')->group(function () {
    Route::resource('kelas', 'KelasController');
//    Route::get('kelas/{slug}/{lesson}', 'KelasController@lesson');
    Route::resource('lesson', 'LessonController');
});

// Partner Auth Controller
Route::middleware(['auth'])->prefix('partner')->namespace('Partner')->name('partner.')->group(function () {
    Route::resource('profile', 'PartnerController');
    Route::resource('voucher', 'VoucherController');
});

// Admin Auth Controller
Route::redirect('/admin', '/admin/kelas');
Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->name('admin.')->group(function () {
    Route::resource('kelas', 'KelasController');
    Route::post('kelas/reorder','KelasController@reorder')->name('kelas.reorder');
});

app/Http/Controllers/Admin/KelasController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Requests\StoreKelasRequest;
use App\Http\Requests\UpdateKelasRequest;
use App\Repositories\KelasRepository;
use App\Repositories\ReorderRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Course;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class KelasController extends Controller
{
    /**
     * @var KelasRepository
     */
    private $kelasRepository;

    public function __construct(KelasRepository $kelasRepository)
    {
        $this->kelasRepository = $kelasRepository;
    }
    public function index(Request $request)
    {
        if($request->ajax()) {
            return datatables($this->kelasRepository->datatable())
                ->addColumn('action','admin.kelas.button')
                ->toJson();
        }
        return view('admin.kelas.index');
    }

    public function create()
    {
        return view('admin.kelas.create');
    }

    public function store(StoreKelasRequest $request)
    {
        $this->kelasRepository->create($request->validated());
        return back()->with(['success' => 'Created']);
    }

    public function edit($id)
    {
        $kelas = $this->kelasRepository->findById($id);
        return view('admin.kelas.edit', compact('kelas'));
    }

    public function update(UpdateKelasRequest $request, $id)
    {
        $this->kelasRepository->update($id, $request->validated());
        return back()->with('success','Updated');
    }

    public function show($id)
    {
        return view('admin.kelas.index');
    }

    public function destroy($id)
    {
        $this->kelasRepository->destroy($id);
        return back()->with('success','Deleted');
    }

    public function push($id)
    {
        $this->kelasRepository->push($id);
        return back()->with('success','Updated');
    }

    public function reorder(Request $request)
    {
        (new ReorderRepository())->reorder($request->positions, Category::class, 'sort_at');
    }
}

app/Http/Controllers/Front/KelasController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Http\Requests\RegisterRequest;
use App\Repositories\KelasRepository;
use App\Repositories\UserRepository;
use App\Repositories\VoucherRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class KelasController extends Controller
{
    private $kelasRepository;

    public function __construct(KelasRepository $kelasRepository)
    {
        $this->kelasRepository = $kelasRepository;
    }
    public function index()
    {
        $items = $this->kelasRepository->getActiveCourse();
        return view('frontend.kelas.index',compact('items'));
    }
    public function show($slug)
    {
        $kelas = $this->kelasRepository->findBySlug($slug);
        return view('frontend.kelas.show',compact('kelas'));
    }
    public function checkout($slug)
    {
        $kelas = $this->kelasRepository->findBySlug($slug);
        return view('frontend.kelas.checkout',compact('kelas'));
    }
    public function check_promo_code(Request $request)
    {
        $kelas = $this->kelasRepository->findBySlug($request->slug);
        $voucher = (new VoucherRepository())->get('voucher_name',$request->promo_code);
        if($voucher){
            $discount = $kelas->price * 0.1; // 10% diskon dari reseller
            $result = [
                'exist' => true,
                'price' => $kelas->price,
                'amount' => rp($kelas->price - $discount),
                'discount' => rp($discount),
                'code' => $voucher->voucher_name,
                'description' => 'Promo spesial <span class="green">10%</span>',
                'message' => ''

            ];

        }else{
            $result = [
                'exist' => false,
                'message' => 'Promo tidak ditemukan.'

            ];
        }

        return response()->json($result);
    }
}

app/Http/Controllers/Student/KelasController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Requests\UpdateProfileRequest;
use App\Repositories\EnrollmentRepository;
use App\Repositories\KelasRepository;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

use Illuminate\Support\Facades\Auth;

class KelasController extends Controller
{
    private $kelasRepository;

    public function __construct(KelasRepository $kelasRepository)
    {
        $this->kelasRepository = $kelasRepository;
    }
    public function index()
    {
        $userCourse = (new EnrollmentRepository())->getUserCourse();
        return view('student.kelas.index',compact('userCourse'));
    }

    public function create()
    {
        # code...
    }

    public function store()
    {
        # code...
    }

    public function show(Request $request, $slug)
    {
//        dd($request->lesson);
        $kelas = $this->kelasRepository->findBySlug($slug);
        $sections = $this->kelasRepository->getSections('course',$kelas->id);
        return view('student.kelas.show',compact('kelas','sections'));
    }

    public function update(UpdateProfileRequest $request)
    {
        $request->validated();
        (new UserRepository())->update(Auth::id(), ['bank_name' => $request->bank_name, 'bank_no_rekening' => $request->bank_no_rekening, 'ktp' => $request->ktp]);
        return redirect()->route('partner.voucher.index')->with('success', 'Data berhasil disimpan');

    }

    public function destroy($id)
    {
        # code...
    }
}

resources/views/admin/kelas/button.blade.php
{{ Form::open(['route' => ['admin.kelas.destroy', $id], 'method' => 'DELETE']) }}
<a href="{{ route('admin.kelas.edit', $id) }}" class="btn btn-primary btn-sm">
    <i class="fa fa-pencil" aria-hidden="true"></i>
    Edit
</a>
<button type="submit" class="btn btn-danger btn-sm">
    <i class="fa fa-trash" aria-hidden="true"></i>
    Delete
</button>
{{ Form::close() }}

resources/views/admin/kelas/create.blade.php
@extends('admin.layout.layout')

@section('title','Create Category')

@section('content')
    @include('admin.layout.validation')
    {{ Form::open(['route' => 'admin.category.store']) }}
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Create Category</h3>
        </div>
        <div class="box-body">
            <div class="row col-md-3">
                <div class="form-group">
                    <label for="">Category Name</label>
                    {{ Form::text('name', null, ['class' => 'form-control','placeholder' => '']) }}
                </div>
            </div>
        </div>
        <div class="box-footer">
            <a href="{{ route('admin.category.index') }}" class="btn btn-warning btn-sm">&laquo; Back</a>
            <button type="submit" class="btn btn-primary btn-sm">Create</button>
        </div>
    </div>
    {{ Form::close() }}
@endsection

resources/views/admin/kelas/edit.blade.php
@extends('admin.layout.layout')

@section('title','Dashboard')

@section('content')
    @include('admin.layout.validation')

    {{ Form::open(['route' => ['admin.category.update', $category->id],'method' => 'PUT']) }}
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Edit Category</h3>
        </div>
        <div class="box-body">
            <div class="form-group">
                <label for="">Category Name</label>
                {{ Form::text('name', $category->name, ['class' => 'form-control','placeholder' => '']) }}
            </div>
        </div>
        <div class="box-footer">
            <a href="{{ route('admin.category.index') }}" class="btn btn-warning btn-sm">&laquo; Back</a>
            <button type="submit" class="btn btn-primary btn-sm">Update</button>
        </div>
    </div>
    {{ Form::close() }}
@endsection

resources/views/admin/kelas/index.blade.php
@extends('admin.layout.layout')

@section('title','Kelas')

@section('content')
    @include('admin.layout.validation')

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Kelas</h3>
            <div class="box-tools pull-right">
                <a href="{{ route('admin.kelas.create') }}" class="btn btn-primary btn-sm">Create</a>
            </div>
        </div>
        <div class="box-body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped datatable">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nama</th>
                        <th style="width: 180px">Action</th>

                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
        <div class="box-footer">
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(function () {
            var table = $('.datatable').DataTable({
                rowReorder: {selector: 'tr', update: false, dataSrc: 'id'},
                processing: true,
                ordering: false,
                serverSide: true,
                ajax: {
                    url: "{{ route('admin.kelas.index') }}"
                },
                columns: [
                    {data: 'id'},
                    {data: 'title'},
                    {data: 'action'},
                ],
                columnDefs: [{targets: [0], visible: false}]
            });

            table.on('row-reorder', function (e, diff, edit) {
                var positions = [];
                diff.forEach(function (val, key) {
                    positions.push({'from': val.oldData, 'to': val.newData});
                });
                $.post("{{ route('admin.kelas.reorder') }}", {
                    positions: positions,
                });
            });
        });
    </script>
@endsection